#!/usr/bin/env bash
# Generates Waybar CSS from colors.sh

command_not_found_handle() {
    return 0
}

COLOR_SH="$HOME/Scripts/ColorGen/Colors"
CSS_FILE="$HOME/Scripts/ColorGen/Colors.css"

if [ ! -f "$COLOR_SH" ]; then
    echo "ERROR: colors.sh not found at $COLOR_SH"
    exit 1
fi

source "$COLOR_SH"

cat > "$CSS_FILE" <<EOF
@define-color bg #$BACKGROUND;
@define-color fg #$PRIMARY;
@define-color fg2 #$SECONDARY;
@define-color accent1 #$ACCENT1;
@define-color accent2 #$ACCENT2;
@define-color accent3 #$ACCENT3;

@define-color grad1 #$GRADIENT1;
@define-color grad2 #$GRADIENT2;
EOF

printf "\e[38;2;0;255;64m┏━  ┏┓┏┓┓ ┏┓┳┓┏┓  ┏┓┏┓┳┓┏┓┳┓┏┓┏┳┓┏┓┳┓╻  ━┓
┃   ┃ ┃┃┃ ┃┃┣┫┗┓  ┃┓┣ ┃┃┣ ┣┫┣┫ ┃ ┣ ┃┃┃   ┃
┗━  ┗┛┗┛┗┛┗┛┛┗┗┛  ┗┛┗┛┛┗┗┛┛┗┛┗ ┻ ┗┛┻┛•  ━┛\e[0m"


