#!/bin/bash

STATE_FILE="$HOME/.config/waybar/Bar_Visible"

# Remove STATE_FILE [if existent]
if [ -f "$STATE_FILE" ]; then rm "$STATE_FILE"; fi

# Kill Waybar
pkill -x waybar

# Relaunch Waybar
sleep 0.2
nohup waybar >/dev/null 2>&1 &
