#!/bin/bash

# VARIABLES
STATE_FILE="$HOME/.config/waybar/Bar_Visible"
AUTO_FILE="$HOME/.config/waybar/Autohide_Visible"
tiled=$(get_tiled_on_active_ws)

# Obtain # of Tiled Windows
get_tiled_on_active_ws(){ local ws=$(hyprctl activeworkspace | awk '/workspace ID/ {print $3}')
hyprctl clients | awk -v ws="$ws" '/^Window /{cur_ws="";floating=""}/^\s*workspace:/{cur_ws=$2}
/^\s*floating:/{floating=$2}cur_ws==ws&&floating==0{count++;cur_ws=""}END{print count+0}'; }

# If Autohide_Visible > Do Not Toggle
send_signals=true
[ -f "$AUTO_FILE" ] && send_signals=false

# 1 Tiled Window = Hide Waybar
	if [ -f "$STATE_FILE" ]; then
		[ "$send_signals" = true ] && pkill -SIGUSR1 waybar
		rm "$STATE_FILE"
	else
		[ "$send_signals" = true ] && pkill -SIGUSR2 waybar
		touch "$STATE_FILE"
	fi
fi

# 0 or 2+ Tiled Windows = Show Waybar
if [ "$tiled" -ge 2 ] || [ "$tiled" -eq 0 ]; then
	if [ -f "$STATE_FILE" ]; then
		[ "$send_signals" = true ] && pkill -SIGUSR1 waybar
		rm "$STATE_FILE"
	else
		[ "$send_signals" = true ] && pkill -SIGUSR2 waybar
		touch "$STATE_FILE"
	fi
else
