#!/bin/bash
set -o pipefail

# Variables
ICON=""
updates="$(CheckUpdates -arch 2>/dev/null)"
tooltip="$(CheckUpdates -arch -tooltip 2>/dev/null)"

# Break Lines
updates="${updates%$'\n'}"
tooltip="${tooltip%$'\n'}"

# Convert to ALL CAPS
updates_upper=$(printf "%s" "$updates" | tr '[:lower:]' '[:upper:]')
tooltip_upper=$(printf "%s" "$tooltip" | tr '[:lower:]' '[:upper:]')

# Output Nothing if = 0
if [[ "$updates_upper" == "0" ]]; then
    jq -cn --arg text "" --arg tooltip "$tooltip_upper" \
       '{text: $text, tooltip: $tooltip}'
    exit 0; fi

# Output Icon & Update #
jq -cn --arg text "[ $ICON $updates_upper ]" --arg tooltip "$tooltip_upper" \
   '{text: $text, tooltip: $tooltip}'
